export enum PreferenceType {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
  ALLERGY = 'ALLERGY' // Critical importance
}

export enum Category {
  FOOD = '食物',
  DRINK = '饮品',
  HOBBY = '爱好',
  GIFT = '礼物',
  CLOTHING = '服饰',
  OTHER = '其他'
}

export interface Preference {
  id: string;
  category: Category;
  item: string;
  type: PreferenceType;
  notes?: string;
}

export interface Person {
  id: string;
  name: string;
  relationship: string; // e.g., Friend, Family, Client
  avatarUrl?: string;
  preferences: Preference[];
  aiSummary?: string; // Generated by Gemini
  lastUpdated: number;
}

export interface GiftSuggestion {
  name: string;
  description: string;
  estimatedPrice?: string;
}

export type ViewState = 'DASHBOARD' | 'PERSON_LIST' | 'PERSON_DETAIL' | 'ADD_PERSON';